version: 2
jobs:
  build:
    docker:
      - image: mmmpa/rust_wasm_node:latest

    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PATH=$PATH:$HOME/node/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.local/bin' >> $BASH_ENV
            source $BASH_ENV

      - checkout
      - restore_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}-{{ checksum "www/package-lock.json" }}

      - run: cargo test
      - run: wasm-pack build --release

      - run: cd www && yarn install
      - run: cd pkg && ln -s ../www/node_modules node_modules
      - run: cd www && yarn lint
      - run: cd www && yarn build

      - save_cache:
          key: project-cache-{{ checksum "Cargo.lock" }}-{{ checksum "www/package-lock.json" }}
          paths:
            - "~/.cargo"
            - "./www/node_modules"
            - "./deploy/node_modules"

      - save_cache:
          key: project-cache-{{ .Revision }}
          paths:
            - "./dist"

  deploy:
    docker:
      - image: mmmpa/rust_wasm_node:latest

    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PATH=$PATH:$HOME/node/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.local/bin' >> $BASH_ENV
            source $BASH_ENV

      - checkout
      - restore_cache:
          key: project-cache-{{ .Revision }}

      - run: cd deployment && yarn install
      - run: cd deployment && yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
